/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package nl.utwente.sosoc.threatintelligence.api;

import nl.utwente.sosoc.threatintelligence.model.IOC;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-03-27T17:40:45.413861+01:00[Europe/Amsterdam]", comments = "Generator version: 7.11.0")
@Validated
@Tag(name = "iocs", description = "the iocs API")
public interface IocsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * DELETE /iocs/{id} : Delete an existing IOC entry
     *
     * @param id Alarm ID (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "deleteIOC",
        summary = "Delete an existing IOC entry",
        tags = { "iocs" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/iocs/{id}"
    )
    
    default ResponseEntity<Void> deleteIOC(
        @Parameter(name = "id", description = "Alarm ID", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /iocs/{id} : Get an IOC entry
     *
     * @param id Alarm ID (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "getIOC",
        summary = "Get an IOC entry",
        tags = { "iocs" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = IOC.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/iocs/{id}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<IOC> getIOC(
        @Parameter(name = "id", description = "Alarm ID", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"match\" : \"Data['email']['source'].contains('malicious.com')\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"threat\" : { \"severity\" : \"high\", \"code\" : \"phishing\", \"technique\" : \"t1566.001\", \"tactic\" : \"ta0001\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /iocs : Get all IOCs
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "getIOCs",
        summary = "Get all IOCs",
        tags = { "iocs" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = IOC.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/iocs",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<IOC>> getIOCs(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"match\" : \"Data['email']['source'].contains('malicious.com')\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"threat\" : { \"severity\" : \"high\", \"code\" : \"phishing\", \"technique\" : \"t1566.001\", \"tactic\" : \"ta0001\" } }, { \"match\" : \"Data['email']['source'].contains('malicious.com')\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"threat\" : { \"severity\" : \"high\", \"code\" : \"phishing\", \"technique\" : \"t1566.001\", \"tactic\" : \"ta0001\" } } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /iocs : Create a new IOC entry
     *
     * @param IOC  (optional)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "postIOC",
        summary = "Create a new IOC entry",
        tags = { "iocs" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/iocs",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> postIOC(
        @Parameter(name = "IOC", description = "") @Valid @RequestBody(required = false) IOC IOC
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /iocs/{id} : Modify an existing IOC entry
     *
     * @param id Alarm ID (required)
     * @param IOC  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "putIOC",
        summary = "Modify an existing IOC entry",
        tags = { "iocs" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/iocs/{id}",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> putIOC(
        @Parameter(name = "id", description = "Alarm ID", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id,
        @Parameter(name = "IOC", description = "", required = true) @Valid @RequestBody IOC IOC
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
