openapi: 3.1.0
info:
  title: Cyber Threat Intelligence Service
  description: CTI manages the collection of intelligence covering existing threads and attacks, as well as previous incidents.
  version: 1.0.0
servers:
  - url: 'localhost'
paths:
  /alarms:
    post:
      operationId: postAlarm
      tags:
        - alarms
      summary: Send an alarm for correlation identification
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../common-schemas/alarms.yaml#/components/schemas/Alarm'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../../common-schemas/iocs.yaml#/components/schemas/IOC'
  /iocs:
    get:
      operationId: getIOCs
      tags:
        - iocs
      summary: Get all IOCs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../../common-schemas/iocs.yaml#/components/schemas/IOC'
    post:
      operationId: postIOC
      tags:
        - iocs
      summary: Create a new IOC entry
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../common-schemas/iocs.yaml#/components/schemas/IOC'
      responses:
        '200':
          description: OK
  /iocs/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
        description: Alarm ID
    get:
      operationId: getIOC
      tags:
        - iocs
      summary: Get an IOC entry
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../../common-schemas/iocs.yaml#/components/schemas/IOC'
    put:
      operationId: putIOC
      tags:
        - iocs
      summary: Modify an existing IOC entry
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../common-schemas/iocs.yaml#/components/schemas/IOC'
        required: true
      responses:
        '200':
          description: OK
    delete:
      operationId: deleteIOC
      tags:
        - iocs
      summary: Delete an existing IOC entry
      responses:
        '200':
          description: OK