server.port=8080
services.logmonitor=http://logmonitor:8080
services.identitymanagement=http://identitymanagement:8080
services.playbookmanagement=http://playbookmanagement:8080
services.threatintelligence=http://threatintelligence:8080
services.userinterface=http://userinterface:8080
spring.main.web-application-type=reactive
#logging.level.org.springframework.cloud.gateway=DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.boot.web=DEBUG
#logging.level.org.springframework.web.filter=DEBUG
#logging.level.reactor.netty=DEBUG