/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package nl.utwente.sosoc.identitymanagement.api;

import java.util.UUID;
import nl.utwente.sosoc.identitymanagement.model.User;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-03-27T16:17:40.733403100+01:00[Europe/Amsterdam]", comments = "Generator version: 7.11.0")
@Validated
@Tag(name = "users", description = "the users API")
public interface UsersApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * DELETE /users/{id} : Delete a user
     *
     * @param id User ID (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "deleteUser",
        summary = "Delete a user",
        tags = { "users" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/users/{id}"
    )
    
    default ResponseEntity<Void> deleteUser(
        @Parameter(name = "id", description = "User ID", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /users/{id} : Get a user
     *
     * @param id User ID (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "getUser",
        summary = "Get a user",
        tags = { "users" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = User.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/users/{id}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<User> getUser(
        @Parameter(name = "id", description = "User ID", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"endpoints\" : [ { \"ip\" : \"ip\", \"host\" : \"host\", \"name\" : \"client-1\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }, { \"ip\" : \"ip\", \"host\" : \"host\", \"name\" : \"client-1\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" } ], \"role\" : \"analyst\", \"name\" : \"Firstname Lastname\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"email\" : \"email\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /users : Get all users
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "getUsers",
        summary = "Get all users",
        tags = { "users" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = User.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/users",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<User>> getUsers(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"endpoints\" : [ { \"ip\" : \"ip\", \"host\" : \"host\", \"name\" : \"client-1\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }, { \"ip\" : \"ip\", \"host\" : \"host\", \"name\" : \"client-1\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" } ], \"role\" : \"analyst\", \"name\" : \"Firstname Lastname\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"email\" : \"email\" }, { \"endpoints\" : [ { \"ip\" : \"ip\", \"host\" : \"host\", \"name\" : \"client-1\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }, { \"ip\" : \"ip\", \"host\" : \"host\", \"name\" : \"client-1\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" } ], \"role\" : \"analyst\", \"name\" : \"Firstname Lastname\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"email\" : \"email\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /users : Create a new user
     *
     * @param user  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "postUser",
        summary = "Create a new user",
        tags = { "users" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/users",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> postUser(
        @Parameter(name = "User", description = "", required = true) @Valid @RequestBody User user
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /users/{id} : Update a user
     *
     * @param id User ID (required)
     * @param user  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "putUser",
        summary = "Update a user",
        tags = { "users" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/users/{id}",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> putUser(
        @Parameter(name = "id", description = "User ID", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id,
        @Parameter(name = "User", description = "", required = true) @Valid @RequestBody User user
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
