openapi: 3.1.0
info:
  title: Security Playbook Management Service
  description: Manages the collection of incident response workflows for different kinds of incidents.
  version: 1.0.0
servers:
  - url: 'https'
paths:
  
