services:
  alertnotify:
    container_name: alertnotify
    build:
      context: ./alertnotify
      dockerfile: ./Dockerfile
    image: alertnotify:latest
    expose:
      - '8080'
    environment:
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}

  automatedresponse:
    container_name: automatedresponse
    build:
      context: ./automatedresponse
      dockerfile: ./Dockerfile
    image: automatedresponse:latest

  identitymanagement:
    container_name: identitymanagement
    build:
      context: ./identitymanagement
      dockerfile: ./Dockerfile
    image: identitymanagement:latest
    expose:
      - '8080'
    depends_on:
      sosoc-db:
        condition: service_healthy
        restart: true

  logmonitor:
    container_name: logmonitor
    build:
      context: ./logmonitor
      dockerfile: ./Dockerfile
    image: logmonitor:latest
    expose:
      - '8080'
    depends_on:
      sosoc-db:
        condition: service_healthy
        restart: true

  playbookmanagement:
    container_name: playbookmanagement
    build:
      context: ./playbookmanagement
      dockerfile: ./Dockerfile
    image: playbookmanagement:latest
    expose:
      - '8080'
    depends_on:
      sosoc-db:
        condition: service_healthy
        restart: true

  threatintelligence:
    container_name: threatintelligence
    build:
      context: ./threatintelligence
      dockerfile: ./Dockerfile
    image: threatintelligence:latest
    expose:
      - '8080'
    depends_on:
      sosoc-db:
        condition: service_healthy
        restart: true

  userinterface:
    container_name: userinterface
    build:
      context: ./userinterface
      dockerfile: ./Dockerfile
    image: userinterface:latest
    ports:
      - '8080:8080'

  sosoc-mq:
    container_name: sosoc-mq
    image: rmohr/activemq:latest
    expose:
      - '61616'
      - '8161'

  sosoc-db:
    container_name: sosoc-db
    image: postgres:latest
    expose:
      - '5432'
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "psql -U $${POSTGRES_USER} -c 'SELECT 1' || exit 1" ]
      interval: 10s
      retries: 10
      start_period: 20s
      timeout: 5s
