openapi: 3.1.0
info:
  title: Log Collection & Monitoring Service
  description: Receives logs from endpoints and responds based on automated detection rules.
  version: 1.0.0
servers:
  - url: 'localhost:8083'
paths:
  /logs:
    get:
      operationId: getLogs
      tags:
        - logs
      summary: Get all log entries
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../../common-schemas/logs.yaml#/components/schemas/LogEntry'
    post:
      operationId: postLog
      tags:
        - logs
      summary: Create a new log entry
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../common-schemas/logs.yaml#/components/schemas/LogEntry'
        required: true
      responses:
        '200':
          description: OK
  /logs/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
        description: Log entry ID
    get:
      operationId: getLog
      tags:
        - logs
      summary: Get a log entry
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../../common-schemas/logs.yaml#/components/schemas/LogEntry'
  /rules:
    get:
      operationId: getRules
      tags:
        - rules
      summary: Get all rules
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../../common-schemas/rules.yaml#/components/schemas/Rule'
    post:
      operationId: postRule
      tags:
        - rules
      summary: create a new rule
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../common-schemas/rules.yaml#/components/schemas/Rule'
        required: true
      responses:
        '200':
          description: OK
  /rules/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
        description: Alarm ID
    get:
      operationId: getRule
      tags:
        - rules
      summary: Get a rule
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../../common-schemas/rules.yaml#/components/schemas/Rule'
    put:
      operationId: putRule
      tags:
        - rules
      summary: Modify a rule
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../common-schemas/rules.yaml#/components/schemas/Rule'
        required: true
      responses:
        '200':
          description: OK
    delete:
      operationId: deleteRule
      tags:
        - rules
      summary: Delete a rule
      responses:
        '200':
          description: OK