openapi: 3.1.0
info:
  title: Alerting & Notification Service
  description: Generates alerts for detected threats and notifies SOC analysts or IT admins via email, SMS, etc.
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /alarms{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
        description: Alarm ID
    put:
      summary: Create or modify an alarm
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                alarm:
                  $ref: '../../common-schemas/alarms.yaml#/components/schemas/Alarm'
                playbook:
                  $ref: '../../common-schemas/playbooks.yaml#/components/schemas/Playbook'