openapi: 3.1.0
info:
  title: Alerting & Notification Service
  description: Generates alerts for detected threats and notifies SOC analysts or IT admins via email, SMS, etc.
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /alarms:
    put:
      summary: Create or modify an alarm
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../common-schemas/alarms.yaml#/components/schemas/Alarm'