openapi: 3.1.0
info:
  title: Alerting & Notification Service
  description: Generates alerts for detected threats and notifies SOC analysts or IT admins via email, SMS, etc.
  version: 1.0.0
servers:
  - url: 'localhost'
paths:
  /workflows:
    post:
      operationId: postWorkflow
      tags:
        - workflows
      summary: Create a new workflow
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../common-schemas/workflows.yaml#/components/schemas/Workflow'
        required: true
      responses:
        '200':
          description: OK
  /workflows/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
        description: Playbook ID
    put:
      operationId: putWorkflow
      tags:
        - workflows
      summary: Update an existing workflow
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../common-schemas/workflows.yaml#/components/schemas/Workflow'
        required: true
      responses:
        '200':
          description: OK