/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package nl.utwente.sosoc.logmonitor.api;

import nl.utwente.sosoc.logmonitor.model.LogEntry;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-04-11T15:54:53.413776400+02:00[Europe/Amsterdam]", comments = "Generator version: 7.12.0")
@Validated
@Tag(name = "logs", description = "the logs API")
public interface LogsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /logs/{id} : Get a log entry
     *
     * @param id Log entry ID (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "getLog",
        summary = "Get a log entry",
        tags = { "logs" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LogEntry.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/logs/{id}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<LogEntry> getLog(
        @Parameter(name = "id", description = "Log entry ID", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"endpoint\" : { \"ip\" : \"ip\", \"host\" : \"host\", \"name\" : \"client-1\" }, \"data\" : { \"key\" : \"\" }, \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"event\" : \"email-received\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /logs : Get all log entries
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "getLogs",
        summary = "Get all log entries",
        tags = { "logs" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = LogEntry.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/logs",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<LogEntry>> getLogs(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"endpoint\" : { \"ip\" : \"ip\", \"host\" : \"host\", \"name\" : \"client-1\" }, \"data\" : { \"key\" : \"\" }, \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"event\" : \"email-received\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }, { \"endpoint\" : { \"ip\" : \"ip\", \"host\" : \"host\", \"name\" : \"client-1\" }, \"data\" : { \"key\" : \"\" }, \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"event\" : \"email-received\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /logs : Create a new log entry
     *
     * @param logEntry  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "postLog",
        summary = "Create a new log entry",
        tags = { "logs" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/logs",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> postLog(
        @Parameter(name = "LogEntry", description = "", required = true) @Valid @RequestBody LogEntry logEntry
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
