/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package nl.utwente.sosoc.logmonitor.api;

import nl.utwente.sosoc.logmonitor.model.Rule;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-03-28T18:16:34.865512200+01:00[Europe/Amsterdam]", comments = "Generator version: 7.11.0")
@Validated
@Tag(name = "rules", description = "the rules API")
public interface RulesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * DELETE /rules/{id} : Delete a rule
     *
     * @param id Alarm ID (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "deleteRule",
        summary = "Delete a rule",
        tags = { "rules" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/rules/{id}"
    )
    
    default ResponseEntity<Void> deleteRule(
        @Parameter(name = "id", description = "Alarm ID", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /rules/{id} : Get a rule
     *
     * @param id Alarm ID (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "getRule",
        summary = "Get a rule",
        tags = { "rules" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Rule.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/rules/{id}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Rule> getRule(
        @Parameter(name = "id", description = "Alarm ID", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"query\" : \"SELECT * FROM logs WHERE type='email-received' AND data->'email'->>'source' NOT LIKE '%example.com' AND timestamp >= NOW() - INTERVAL '5 minutes';\n\", \"name\" : \"external email\", \"interval\" : \"*/5 * * * *\", \"threshold\" : \"\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"threat\" : { \"severity\" : \"high\", \"code\" : \"phishing\", \"technique\" : \"t1566.001\", \"tactic\" : \"ta0001\" }, \"fields\" : [ { \"field\" : \"field\", \"type\" : \"type\" }, { \"field\" : \"field\", \"type\" : \"type\" } ], \"group\" : \"\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /rules : Get all rules
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "getRules",
        summary = "Get all rules",
        tags = { "rules" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Rule.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/rules",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<Rule>> getRules(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"query\" : \"SELECT * FROM logs WHERE type='email-received' AND data->'email'->>'source' NOT LIKE '%example.com' AND timestamp >= NOW() - INTERVAL '5 minutes';\n\", \"name\" : \"external email\", \"interval\" : \"*/5 * * * *\", \"threshold\" : \"\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"threat\" : { \"severity\" : \"high\", \"code\" : \"phishing\", \"technique\" : \"t1566.001\", \"tactic\" : \"ta0001\" }, \"fields\" : [ { \"field\" : \"field\", \"type\" : \"type\" }, { \"field\" : \"field\", \"type\" : \"type\" } ], \"group\" : \"\" }, { \"query\" : \"SELECT * FROM logs WHERE type='email-received' AND data->'email'->>'source' NOT LIKE '%example.com' AND timestamp >= NOW() - INTERVAL '5 minutes';\n\", \"name\" : \"external email\", \"interval\" : \"*/5 * * * *\", \"threshold\" : \"\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"threat\" : { \"severity\" : \"high\", \"code\" : \"phishing\", \"technique\" : \"t1566.001\", \"tactic\" : \"ta0001\" }, \"fields\" : [ { \"field\" : \"field\", \"type\" : \"type\" }, { \"field\" : \"field\", \"type\" : \"type\" } ], \"group\" : \"\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /rules : create a new rule
     *
     * @param rule  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "postRule",
        summary = "create a new rule",
        tags = { "rules" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/rules",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> postRule(
        @Parameter(name = "Rule", description = "", required = true) @Valid @RequestBody Rule rule
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /rules/{id} : Modify a rule
     *
     * @param id Alarm ID (required)
     * @param rule  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "putRule",
        summary = "Modify a rule",
        tags = { "rules" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/rules/{id}",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> putRule(
        @Parameter(name = "id", description = "Alarm ID", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id,
        @Parameter(name = "Rule", description = "", required = true) @Valid @RequestBody Rule rule
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
