openapi: 3.1.0
info:
  title: Identity Management Service
  description: Manages user access, authentication, and privileges, as well as end-point devices.
  version: 1.0.0
servers:
  - url: 'http://localhost:8082'
paths:
  /users:
    get:
      operationId: getUsers
      tags:
        - users
      summary: Get all users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../../common-schemas/users.yaml#/components/schemas/User'
    post:
      operationId: postUser
      tags:
        - users
      summary: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../common-schemas/users.yaml#/components/schemas/User'
        required: true
      responses:
        '200':
          description: OK
  /users/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
        description: User ID
    get:
      operationId: getUser
      tags:
        - users
      summary: Get a user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../../common-schemas/users.yaml#/components/schemas/User'
    put:
      operationId: putUser
      tags:
        - users
      summary: Update a user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../common-schemas/users.yaml#/components/schemas/User'
        required: true
      responses:
        '200':
          description: OK
    delete:
      operationId: deleteUser
      tags:
        - users
      summary: Delete a user
      responses:
        '200':
          description: OK
  /actions:
    post:
      operationId: postAction
      tags:
        - actions
      summary: Create a new action
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../common-schemas/actions.yaml#/components/schemas/Action'
        required: true
      responses:
        '200':
          description: OK