components:
  schemas:
    Playbook:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: phishing email
        description:
          type: string
          example: quarantines endpoint
        trigger:
          oneOf:
            - type: object
              properties:
                match:
                  type: string
                  format: SpEL
                  example: Threat.Code == 'phishing'
            - type: object
              properties:
                rule:
                  type: string
                  format: uuid
        steps:
          type: array
          items:
            $ref: '#/components/schemas/Step'
          minItems: 1
    Step:
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          enum:
            - human
            - auto
        name:
          type: string
          example: await analyst confirmation
        action:
          type: string
        next:
          oneOf:
            - type: array
              items:
                type: object
                properties:
                  condition:
                    type: string
                    examples:
                      - no threat
                      - high threat
                  next:
                    type: string
                    format: uuid
              minItems: 2
            - type: string
              format: uuid
              nullable: true