components:
  schemas:
    Playbook:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        steps:
          type: array
          items:
            $ref: '#/components/schemas/Step'
          minItems: 1
    Step:
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          enum:
            - human
            - auto
        name:
          type: string
        action:
          type: string
        next:
          oneOf:
            - type: array
              items:
                type: object
                properties:
                  condition:
                    type: string
                  next:
                    type: string
                    format: uuid
              minItems: 2
            - type: string
              format: uuid
              nullable: true