components:
  schemas:
    Playbook:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: phishing email
        description:
          type: string
          example: quarantines endpoint
        trigger:
          type: string
          format: SpEL
          example: Threat.Code == 'phishing'
        firstStep:
          type: string
        steps:
          type: array
          items:
            $ref: '#/components/schemas/Step'
          minItems: 1
      required:
        - name
        - description
        - trigger
        - firstStep
        - steps
    Step:
      type: object
      properties:
        name:
          type: string
          example: await analyst confirmation
        type:
          type: string
          enum:
            - human
            - auto
        action:
          type: string
        next:
          type: array
          items:
            $ref: '#/components/schemas/ConditionalNext'
      required:
        - name
        - type
        - action
        - next
    ConditionalNext:
      type: object
      properties:
        condition:
          type: string
          examples:
            - no threat
            - high threat
        name:
          type: string
      required:
        - condition
        - name