apiVersion: apps/v1
kind: Deployment
metadata:
  name: automatedresponse
  namespace: soa-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: automatedresponse
  template:
    metadata:
      labels:
        app: automatedresponse
    spec:
      initContainers:
         # ToDO: wait for DB to be up for all services and remove this
        - name: wait-for-db
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z sosoc-db 5432; do
                echo "Waiting for DB"; sleep 2; 
              done;
      containers:
        - name: automatedresponse
          image: automatedresponse:latest
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: automatedresponse
  namespace: soa-project
spec:
  selector:
    app: automatedresponse
  clusterIP: None  # uses message queue
