apiVersion: apps/v1
kind: Deployment
metadata:
  name: logmonitor
  namespace: soa-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logmonitor
  template:
    metadata:
      labels:
        app: logmonitor
    spec:
      containers:
        - name: logmonitor
          image: logmonitor:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: logmonitor
spec:
  selector:
    app: logmonitor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
