apiVersion: apps/v1
kind: Deployment
metadata:
  name: playbookmanagement
  namespace: soa-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playbookmanagement
  template:
    metadata:
      labels:
        app: playbookmanagement
    spec:
      containers:
        - name: playbookmanagement
          image: playbookmanagement:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: playbookmanagement
  namespace: soa-project
spec:
  # type: ToDO: loadbalancer for all
  selector:
    app: playbookmanagement
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
