apiVersion: v1
kind: ConfigMap
metadata:
  name: sosoc-db-init-sql
  namespace: soa-project
data:
  init.sql: |
    CREATE DATABASE logmonitor;
    CREATE DATABASE playbookmanagement;
    CREATE DATABASE identitymanagement;
    CREATE DATABASE threatintelligence;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sosoc-db
  namespace: soa-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sosoc-db
  template:
    metadata:
      labels:
        app: sosoc-db
    spec:
      containers:
        - name: sosoc-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "admin"
          volumeMounts:
            - name: postgres-data-volume
              mountPath: /var/lib/postgresql/data
            - name: init-sql-volume
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-data-volume
          hostPath:
            path: "/your/absolute/path/to/postgres_data"
            type: DirectoryOrCreate
        - name: init-sql-volume
          configMap:
            name: sosoc-db-init-sql
---
apiVersion: v1
kind: Service
metadata:
  name: sosoc-db
  namespace: soa-project
spec:
  selector:
    app: sosoc-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
