apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sosoc-mq
  namespace: soa-project
spec:
  serviceName: sosoc-mq
  replicas: 1
  selector:
    matchLabels:
      app: sosoc-mq
  template:
    metadata:
      labels:
        app: sosoc-mq
    spec:
      containers:
        - name: activemq
          image: rmohr/activemq:latest
          ports:
            - containerPort: 61616
            - containerPort: 8161
          volumeMounts:
            - name: data
              mountPath: /opt/activemq/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sosoc-mq
  namespace: soa-project
spec:
  type: ClusterIP
  selector:
    app: sosoc-mq
  ports:
    - name: mq
      port: 61616
      targetPort: 61616
    - name: web
      port: 8161
      targetPort: 8161

