apiVersion: apps/v1
kind: Deployment
metadata:
  name: threatintelligence
  namespace: soa-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: threatintelligence
  template:
    metadata:
      labels:
        app: threatintelligence
    spec:
      containers:
        - name: threatintelligence
          image: threatintelligence:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: threatintelligence
  namespace: soa-project
spec:
  selector:
    app: threatintelligence
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
