openapi: 3.1.0
info:
  title: Automated Response Service
  description: Takes automated actions when threats are detected.
    For example, disabling accounts, blocking network sources, or quarantining endpoint devices.
  version: 1.0.0
servers:
  - url: 'localhost'
paths:
  /workflows:
    post:
      summary: Create a new workflow
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../common-schemas/workflows.yaml#/components/schemas/Workflow'
        required: true
  /workflows/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
        description: Playbook ID
    put:
      summary: Update an existing workflow
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../common-schemas/workflows.yaml#/components/schemas/Workflow'
        required: true