server.port=8084
spring.jackson.date-format=nl.utwente.sosoc.playbookmanagement.util.RFC3339DateFormat
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.activemq.broker-url=tcp://sosoc-mq:61616
spring.activemq.user=admin
spring.activemq.password=admin
